language: rust
rust:
  - 1.41.0

script:
  - cd $TRAVIS_BUILD_DIR/mancala/client && cargo test --verbose
  - cd $TRAVIS_BUILD_DIR/mancala/server && cargo test --verbose
  - cd $TRAVIS_BUILD_DIR/mancala/protocol && cargo test --verbose